@startuml
'https://plantuml.com/class-diagram

class App {
+main( String[] args )
+printInvalid()
+parseJsonFile()
+printProduct(String productInJSON, JSONArray arrayOfProducts)
+askForProduct()
}

@enduml